### ISSUE TITLE
Mission 2 - Inception : Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [arik-le/A-Home-For-Every-Child#2]
- לא הוספתם את ראובן לפרויקט

- תכנון זמנים טעון שיפור, לדוגמה:

> Sketch of the site appearance, domain name selection, site features,  14 days

ארבעה-עשר יום זה המון למשימה זו, לעומת זאת הקדשתם יום אחד ללמידה:

> Learning and understanding our database and work enviroment, 1 day

רשמתם שאתם מתכוונים לעבוד בצורת אג׳ייל אבל התכנון שהבאתם לא מספק לכם גמישות לשינויים במהלך העבודה, צריך לבחון שוב את לוח הזמנים ולהשאיר מקום לחוות דעת של הלקוח ולשינויים תוך כדי תנועה.

יש צורך לספר עוד טיפה על כל חבר צוות.

**Comment by royok17** [comment]
לגבי ההוספה של ראובן, בוצע.
לגבי התכנון זמנים. תוקן.
אני יכול לספר על החברים מכאן ועד להודעה חדשה, אבל לא מובן איזה סוג של אינפורמציה אתם רוצים שנפרסם כאן..

**Comment by arik-le** [comment]
@kob-e 

הכל תוקן , נשמח אם תבדוק
