### ISSUE TITLE
Mission 4 - SDS: Feedback

### ISSUE THREAD

**Issue by YaakovHatam** [arik-le/A-Home-For-Every-Child#44]
- מה עם בדיקות?
- יהיה נחמד אם תוסיפו לדף תוכן עניינים

**Comment by royok17** [comment]
הוספנו תוכן עניינים , ולפי הבנתי הבדיקות היו שדה רשות.....
דבר אחר על פי הציונים שהועלו לאתר
ב-UML קיבלנו 70
ב- section קיבלנו 80 
וב -update & summary לא קיבלנו ציון
אני רוצה לדעת למה קיבלנו את כל אחד מהציונים ולשמוע את עצתך באיך אנחנו יכולים לעגל אותם למאיות 
@kob-e

**Comment by YaakovHatam** [comment]
Good work.
