### ISSUE TITLE
dont clear the previous users in edit users option

### ISSUE THREAD

**Issue by arik-le** [arik-le/A-Home-For-Every-Child#60]
when showing user per clubhouse in edit page - dont clear the previous 

[link](https://github.com/arik-le/A-Home-For-Every-Child/commit/178064704dd9606faa6a32c7517f99b2528c1fbf#commitcomment-22307681) to the bug

**Comment by royok17** [comment]
i fix it look this link
https://github.com/arik-le/A-Home-For-Every-Child/commit/191dc42522a43b4e7809c5873a3f90d7d920e8fd
